import jsPDF from "jspdf";
import type { NormalizedFeedback } from "@/lib/normalizeFeedback";

const MARGIN = 16;
const PAGE_W = 210;
const PAGE_H = 297;
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H = 5;
const MONO = "courier"; // jsPDF built-in monospace

const COLORS = {
  black: [18, 18, 18] as const,
  dark: [40, 40, 40] as const,
  body: [55, 55, 55] as const,
  label: [100, 100, 100] as const,
  muted: [150, 150, 150] as const,
  light: [200, 200, 200] as const,
  divider: [220, 220, 220] as const,
  white: [255, 255, 255] as const,
  headerBg: [20, 20, 20] as const,
  // Status colors
  high: [220, 70, 50] as const,
  highBg: [255, 240, 237] as const,
  med: [200, 155, 30] as const,
  medBg: [255, 248, 230] as const,
  low: [140, 140, 140] as const,
  lowBg: [240, 240, 240] as const,
  good: [50, 160, 80] as const,
  goodBg: [235, 250, 240] as const,
};

const modeLabels: Record<string, string> = {
  technical: "Technical Analysis",
  musical: "Musical Analysis",
  perception: "Perception Analysis",
};

const modeWhatWorksLabel: Record<string, string> = {
  technical: "What Works",
  musical: "What Lands",
  perception: "What Translates",
};

const modeFixOneLabel: Record<string, string> = {
  technical: "If You Fix Only One Thing",
  musical: "Focus Here",
  perception: "Urgent Fix",
};

// ─── Footer on every page ───
function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const footerY = PAGE_H - 12;
  // thin top border
  doc.setDrawColor(...COLORS.divider);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, footerY - 3, PAGE_W - MARGIN, footerY - 3);
  // left text
  doc.setFontSize(6.5);
  doc.setFont(MONO, "normal");
  doc.setTextColor(...COLORS.muted);
  doc.text("GENERATED BY SECONDEAR", MARGIN, footerY);
  // right text
  doc.text(`${pageNum} / ${totalPages}`, PAGE_W - MARGIN, footerY, { align: "right" });
}

// ─── Page break check ───
function checkPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_H - 22) {
    doc.addPage();
    return MARGIN + 4;
  }
  return y;
}

// ─── Wrapped text ───
function addWrapped(doc: jsPDF, text: string, x: number, y: number, maxW: number, lh = LINE_H): number {
  const lines = doc.splitTextToSize(text, maxW) as string[];
  for (const line of lines) {
    y = checkPage(doc, y, lh);
    doc.text(line, x, y);
    y += lh;
  }
  return y;
}

// ─── Section title (uppercase, letter-spaced, with divider) ───
function sectionTitle(doc: jsPDF, title: string, y: number): number {
  y = checkPage(doc, y, 14);
  doc.setFontSize(8.5);
  doc.setFont(MONO, "bold");
  doc.setTextColor(...COLORS.dark);
  // Manual letter-spacing via characterSpacing
  doc.text(title.toUpperCase(), MARGIN, y, { charSpace: 1.2 });
  y += 2.5;
  doc.setDrawColor(...COLORS.divider);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 5;
  return y;
}

// ─── Status badge pill ───
function drawStatusBadge(doc: jsPDF, status: string, x: number, y: number): number {
  const s = status.toLowerCase();
  let bg: readonly number[], fg: readonly number[];
  if (s.includes("good") || s.includes("balanced")) {
    bg = COLORS.goodBg; fg = COLORS.good;
  } else if (s.includes("needs") || s.includes("clipping") || s.includes("compressed")) {
    bg = COLORS.highBg; fg = COLORS.high;
  } else if (s.includes("acceptable") || s.includes("borderline") || s.includes("review") || s.includes("wide")) {
    bg = COLORS.medBg; fg = COLORS.med;
  } else {
    bg = COLORS.lowBg; fg = COLORS.low;
  }

  doc.setFontSize(6);
  doc.setFont(MONO, "bold");
  const tw = doc.getTextWidth(status.toUpperCase()) + 4;
  const pillH = 4.5;
  const pillY = y - 3.2;

  // pill background
  doc.setFillColor(bg[0], bg[1], bg[2]);
  doc.roundedRect(x, pillY, tw, pillH, 1, 1, "F");
  // pill text
  doc.setTextColor(fg[0], fg[1], fg[2]);
  doc.text(status.toUpperCase(), x + 2, y);

  return x + tw + 2;
}

// ─── Waveform visualization ───
function drawWaveform(doc: jsPDF, items: { timestampSec: number; title: string }[], y: number): number {
  if (items.length === 0) return y;
  y = checkPage(doc, y, 22);

  const barX = MARGIN;
  const barW = CONTENT_W;
  const barH = 6;
  const maxSec = Math.max(...items.map(i => i.timestampSec), 60);

  // Track bar background
  doc.setFillColor(235, 235, 235);
  doc.roundedRect(barX, y, barW, barH, 1.5, 1.5, "F");

  // Inner gradient-like fill
  doc.setFillColor(210, 210, 210);
  doc.roundedRect(barX, y, barW, barH, 1.5, 1.5, "F");
  doc.setFillColor(225, 225, 225);
  doc.roundedRect(barX, y + 1, barW, barH - 2, 1, 1, "F");

  // Marker lines
  for (const item of items) {
    const ratio = Math.min(item.timestampSec / maxSec, 1);
    const mx = barX + ratio * barW;

    // Vertical line
    doc.setDrawColor(...COLORS.high);
    doc.setLineWidth(0.5);
    doc.line(mx, y - 1, mx, y + barH + 1);

    // Dot
    doc.setFillColor(...COLORS.high);
    doc.circle(mx, y + barH / 2, 1, "F");
  }

  y += barH + 3;

  // Marker labels below (compact, only show first few to fit)
  doc.setFontSize(5);
  doc.setFont(MONO, "normal");
  doc.setTextColor(...COLORS.label);

  const maxLabels = Math.min(items.length, 8);
  for (let i = 0; i < maxLabels; i++) {
    const item = items[i];
    const ratio = Math.min(item.timestampSec / maxSec, 1);
    const mx = barX + ratio * barW;
    const label = item.title.length > 18 ? item.title.slice(0, 17) + "…" : item.title;
    // Alternate above/below to avoid overlap
    const labelY = y + (i % 2 === 0 ? 0 : 4);
    doc.text(label, Math.min(Math.max(mx - 4, barX), barX + barW - 20), labelY);
  }

  return y + 10;
}

// ════════════════════════════════════════════════════════════════
// MAIN EXPORT
// ════════════════════════════════════════════════════════════════
export function exportAnalysisPdf(n: NormalizedFeedback, releaseReadiness: string | null) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 0;

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // ═══════════════════════════════════════════
  // HEADER — black bar
  // ═══════════════════════════════════════════
  const headerH = 22;
  doc.setFillColor(...COLORS.headerBg);
  doc.rect(0, 0, PAGE_W, headerH, "F");

  // SECONDEAR logo left
  doc.setFontSize(11);
  doc.setFont(MONO, "bold");
  doc.setTextColor(...COLORS.white);
  doc.text("SECONDEAR", MARGIN, 10, { charSpace: 2.5 });

  // Track name + mode right
  doc.setFontSize(8);
  doc.setFont(MONO, "bold");
  doc.setTextColor(220, 220, 220);
  const trackDisplay = n.trackName.length > 30 ? n.trackName.slice(0, 29) + "…" : n.trackName;
  doc.text(trackDisplay, PAGE_W - MARGIN, 9, { align: "right" });

  doc.setFontSize(7);
  doc.setFont(MONO, "normal");
  doc.setTextColor(160, 160, 160);
  doc.text(`${modeLabels[n.mode] || n.mode}  ·  ${dateStr}`, PAGE_W - MARGIN, 15, { align: "right" });

  y = headerH + 8;

  // ═══════════════════════════════════════════
  // EXECUTIVE SUMMARY CHIPS
  // ═══════════════════════════════════════════
  const chips: { label: string; value: string }[] = [];
  if (n.topIssue) chips.push({ label: "TOP ISSUE", value: n.topIssue });
  if (n.biggestWin) chips.push({ label: "BIGGEST WIN", value: n.biggestWin });
  if (releaseReadiness) chips.push({ label: "RELEASE", value: releaseReadiness });

  if (chips.length > 0) {
    for (const chip of chips) {
      y = checkPage(doc, y, 8);
      doc.setFontSize(6.5);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...COLORS.label);
      doc.text(chip.label, MARGIN, y, { charSpace: 0.8 });

      doc.setFontSize(8);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...COLORS.body);
      doc.text(chip.value, MARGIN + 30, y);
      y += LINE_H + 1;
    }
    y += 3;
  }

  // ═══════════════════════════════════════════
  // WAVEFORM VISUALIZATION
  // ═══════════════════════════════════════════
  if (n.timelineItems.length > 0) {
    y = drawWaveform(doc, n.timelineItems, y);
  }

  // ═══════════════════════════════════════════
  // OVERALL IMPRESSION
  // ═══════════════════════════════════════════
  if (n.overallImpression) {
    y = sectionTitle(doc, "Overall Impression", y);
    doc.setFontSize(8.5);
    doc.setFont(MONO, "normal");
    doc.setTextColor(...COLORS.body);
    y = addWrapped(doc, n.overallImpression, MARGIN, y, CONTENT_W);
    y += 6;
  }

  // ═══════════════════════════════════════════
  // TIMELINE FEEDBACK
  // ═══════════════════════════════════════════
  if (n.timelineItems.length > 0) {
    y = sectionTitle(doc, "Timeline Feedback", y);
    for (const item of n.timelineItems) {
      y = checkPage(doc, y, 16);
      // Timestamp + title
      doc.setFontSize(8);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...COLORS.dark);
      const ts = item.timestampSec >= 0 ? item.timestamp : "";
      if (ts) {
        // timestamp in a subtle box
        const tsW = doc.getTextWidth(ts) + 3;
        doc.setFillColor(240, 240, 240);
        doc.roundedRect(MARGIN, y - 3.2, tsW, 4.5, 1, 1, "F");
        doc.setTextColor(...COLORS.label);
        doc.setFontSize(6.5);
        doc.text(ts, MARGIN + 1.5, y);
        doc.setFontSize(8);
        doc.setFont(MONO, "bold");
        doc.setTextColor(...COLORS.dark);
        doc.text(item.title, MARGIN + tsW + 2, y);
      } else {
        doc.text(item.title, MARGIN, y);
      }
      y += LINE_H;

      if (item.description) {
        doc.setFontSize(7.5);
        doc.setFont(MONO, "normal");
        doc.setTextColor(...COLORS.body);
        y = addWrapped(doc, item.description, MARGIN + 2, y, CONTENT_W - 2, 4.5);
      }
      if (item.actionText) {
        doc.setFontSize(6.5);
        doc.setFont(MONO, "bold");
        doc.setTextColor(...COLORS.label);
        doc.text(item.actionLabel, MARGIN + 2, y, { charSpace: 0.6 });
        doc.setFont(MONO, "normal");
        doc.setTextColor(...COLORS.body);
        y = addWrapped(doc, item.actionText, MARGIN + 14, y, CONTENT_W - 14, 4.5);
      }
      y += 2.5;
    }
    y += 3;
  }

  // ═══════════════════════════════════════════
  // TECHNICAL METRICS — two-column table
  // ═══════════════════════════════════════════
  const m = n.metrics;
  const metricEntries: { label: string; value: string; status: string }[] = [];
  if (m.integratedLufs !== null)
    metricEntries.push({ label: "Integrated LUFS", value: `${m.integratedLufs.toFixed(1)} LUFS`, status: getMetricStatus("lufs", m.integratedLufs) });
  if (m.shortTermLufs !== null)
    metricEntries.push({ label: "Short-Term LUFS", value: `${m.shortTermLufs.toFixed(1)} LUFS`, status: getMetricStatus("stlufs", m.shortTermLufs) });
  if (m.dynamicRange !== null)
    metricEntries.push({ label: "Dynamic Range", value: `${m.dynamicRange.toFixed(1)} dB`, status: getMetricStatus("dr", m.dynamicRange) });
  if (m.peakDbtp !== null)
    metricEntries.push({ label: "Peak dBTP", value: `${m.peakDbtp.toFixed(1)} dBTP`, status: getMetricStatus("peak", m.peakDbtp) });
  if (m.stereoCorrelation !== null)
    metricEntries.push({ label: "Stereo Correlation", value: m.stereoCorrelation.toFixed(2), status: getMetricStatus("stereo", m.stereoCorrelation) });
  if (m.crestFactor !== null)
    metricEntries.push({ label: "Crest Factor", value: `${m.crestFactor.toFixed(1)} dB`, status: getMetricStatus("crest", m.crestFactor) });
  if (m.subKickRatio !== null)
    metricEntries.push({ label: "Sub/Kick Ratio", value: m.subKickRatio.toFixed(2), status: getMetricStatus("sub", m.subKickRatio) });

  if (metricEntries.length > 0) {
    y = sectionTitle(doc, "Technical Metrics", y);

    const colLabel = MARGIN;
    const colValue = MARGIN + 50;
    const colStatus = MARGIN + 80;
    const rowH = 6.5;

    // Table header
    doc.setFontSize(6);
    doc.setFont(MONO, "bold");
    doc.setTextColor(...COLORS.label);
    doc.text("METRIC", colLabel, y, { charSpace: 0.8 });
    doc.text("VALUE", colValue, y, { charSpace: 0.8 });
    doc.text("STATUS", colStatus, y, { charSpace: 0.8 });
    y += 2;
    doc.setDrawColor(...COLORS.divider);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 3.5;

    for (let i = 0; i < metricEntries.length; i++) {
      y = checkPage(doc, y, rowH);
      const me = metricEntries[i];

      // Alternating row bg
      if (i % 2 === 0) {
        doc.setFillColor(248, 248, 248);
        doc.rect(MARGIN, y - 3.5, CONTENT_W, rowH, "F");
      }

      // Label
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...COLORS.dark);
      doc.text(me.label, colLabel + 1, y);

      // Value
      doc.setFont(MONO, "bold");
      doc.setTextColor(...COLORS.black);
      doc.text(me.value, colValue + 1, y);

      // Status badge
      drawStatusBadge(doc, me.status, colStatus + 1, y);

      y += rowH;
    }
    y += 6;
  }

  // ═══════════════════════════════════════════
  // FULL ANALYSIS
  // ═══════════════════════════════════════════
  const faCards = getFullAnalysisCards(n);
  const hasFA = faCards.some((c) => c.text);
  if (hasFA) {
    y = sectionTitle(doc, "Deep Read", y);
    for (const card of faCards) {
      if (!card.text) continue;
      y = checkPage(doc, y, 14);
      doc.setFontSize(7.5);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...COLORS.dark);
      doc.text(card.label.toUpperCase(), MARGIN, y, { charSpace: 0.6 });
      y += LINE_H;
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...COLORS.body);
      y = addWrapped(doc, card.text, MARGIN + 1, y, CONTENT_W - 1, 4.5);
      y += 2.5;
    }
    y += 3;
  }

  // ═══════════════════════════════════════════
  // WHAT WORKS
  // ═══════════════════════════════════════════
  if (n.whatWorks.length > 0) {
    y = sectionTitle(doc, modeWhatWorksLabel[n.mode] || "What Works", y);
    for (const item of n.whatWorks) {
      y = checkPage(doc, y, 12);
      doc.setFontSize(7.5);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...COLORS.dark);
      doc.text("✓  " + item.title, MARGIN, y);
      y += LINE_H;
      if (item.description) {
        doc.setFont(MONO, "normal");
        doc.setTextColor(...COLORS.body);
        y = addWrapped(doc, item.description, MARGIN + 5, y, CONTENT_W - 5, 4.5);
      }
      y += 2;
    }
    y += 3;
  }

  // ═══════════════════════════════════════════
  // FIX ONE THING
  // ═══════════════════════════════════════════
  if (n.ifFixOneThing && (n.ifFixOneThing.title || n.ifFixOneThing.how)) {
    y = sectionTitle(doc, modeFixOneLabel[n.mode] || "If You Fix Only One Thing", y);
    y = checkPage(doc, y, 16);

    // Highlight box
    doc.setFillColor(...COLORS.highBg);
    doc.setDrawColor(...COLORS.high);
    doc.setLineWidth(0.3);

    const boxStart = y - 3;
    let boxContent = y;

    if (n.ifFixOneThing.title) {
      doc.setFontSize(8.5);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...COLORS.high);
      doc.text(n.ifFixOneThing.title, MARGIN + 4, boxContent);
      boxContent += 5;
    }
    if (n.ifFixOneThing.why) {
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...COLORS.body);
      boxContent = addWrapped(doc, "Why: " + n.ifFixOneThing.why, MARGIN + 4, boxContent, CONTENT_W - 8, 4.5);
    }
    if (n.ifFixOneThing.how) {
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...COLORS.body);
      boxContent = addWrapped(doc, "How: " + n.ifFixOneThing.how, MARGIN + 4, boxContent, CONTENT_W - 8, 4.5);
    }

    const boxH = boxContent - boxStart + 2;
    // Draw box behind (we re-draw text, or we accept layering — jsPDF draws in order, so draw box first via a trick)
    // Actually we already drew text. Let's just draw border lines around it.
    doc.setDrawColor(220, 80, 60);
    doc.setLineWidth(0.4);
    doc.line(MARGIN, boxStart, MARGIN, boxStart + boxH); // left accent line

    y = boxContent + 5;
  }

  // ═══════════════════════════════════════════
  // YOUR FOCUS
  // ═══════════════════════════════════════════
  if (n.yourFocus.question) {
    y = sectionTitle(doc, "Your Focus", y);
    y = checkPage(doc, y, 14);

    doc.setFontSize(6.5);
    doc.setFont(MONO, "bold");
    doc.setTextColor(...COLORS.label);
    doc.text("YOU ASKED", MARGIN, y, { charSpace: 0.8 });
    y += LINE_H;
    doc.setFontSize(7.5);
    doc.setFont(MONO, "normal");
    doc.setTextColor(...COLORS.body);
    y = addWrapped(doc, `"${n.yourFocus.question}"`, MARGIN + 2, y, CONTENT_W - 2, 4.5);
    y += 2;
    if (n.yourFocus.response) {
      doc.setFontSize(6.5);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...COLORS.label);
      doc.text("RESPONSE", MARGIN, y, { charSpace: 0.8 });
      y += LINE_H;
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...COLORS.body);
      y = addWrapped(doc, n.yourFocus.response, MARGIN + 2, y, CONTENT_W - 2, 4.5);
    }
  }

  // ═══════════════════════════════════════════
  // FOOTERS on all pages
  // ═══════════════════════════════════════════
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i, pageCount);
  }

  const safeName = n.trackName.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 40);
  doc.save(`SecondEar_${safeName}.pdf`);
}

// ─── Helpers ───

function getFullAnalysisCards(n: NormalizedFeedback) {
  const fa = n.fullAnalysis;
  if (n.mode === "musical") {
    return [
      { label: "Energy Arc", text: fa.energyArc },
      { label: "Section Contrast", text: fa.sectionContrast },
      { label: "Groove Continuity", text: fa.grooveContinuity },
      { label: "Hook Clarity", text: fa.hookClarity },
    ];
  }
  if (n.mode === "perception") {
    return [
      { label: "Sub & Low Translation", text: fa.subLowTranslation },
      { label: "Headroom & Transients", text: fa.headroomTransients },
      { label: "Stereo Fold-Down", text: fa.stereoFoldDown },
      { label: "Listener Fatigue", text: fa.listenerFatigue },
    ];
  }
  return [
    { label: "Mix Balance", text: fa.mixBalance },
    { label: "Dynamics & Loudness", text: fa.dynamics },
    { label: "Stereo & Space", text: fa.stereoSpace },
    { label: "Frequency Balance", text: fa.frequencyBalance },
  ];
}

function getMetricStatus(type: string, val: number): string {
  switch (type) {
    case "lufs":
      if (val >= -14 && val <= -9) return "Good";
      if (val >= -16 && val <= -7) return "Acceptable";
      return "Needs attention";
    case "stlufs":
      if (val >= -12 && val <= -7) return "Good";
      return "Review";
    case "dr":
      if (val >= 6 && val <= 14) return "Good";
      if (val >= 4) return "Acceptable";
      return "Needs attention";
    case "peak":
      if (val <= -1) return "Good";
      if (val <= 0) return "Borderline";
      return "Clipping";
    case "stereo":
      if (val >= 0.5) return "Good";
      if (val >= 0.2) return "Wide";
      return "Very wide";
    case "crest":
      if (val >= 8 && val <= 18) return "Good";
      if (val >= 5) return "Acceptable";
      return "Compressed";
    case "sub":
      if (val >= 0.3 && val <= 0.7) return "Balanced";
      return "Review";
    default:
      return "";
  }
}
