import jsPDF from "jspdf";
import type { NormalizedFeedback } from "@/lib/normalizeFeedback";

const MARGIN_L = 20;
const MARGIN_R = 20;
const PAGE_W = 210;
const PAGE_H = 297;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
const LINE_H = 5;
const MONO = "courier"; // jsPDF built-in monospace

const C = {
  black: [17, 17, 17] as const,
  dark: [34, 34, 34] as const,
  body: [68, 68, 68] as const,
  label: [136, 136, 136] as const,
  muted: [170, 170, 170] as const,
  fixLabel: [136, 136, 136] as const,
  divider: [221, 221, 221] as const,
  lightDivider: [224, 224, 224] as const,
  white: [255, 255, 255] as const,
  headerBg: [17, 17, 17] as const,
  headerFg: [232, 232, 224] as const,
  // Summary table
  summaryLabelBg: [245, 245, 243] as const,
  summaryBorder: [17, 17, 17] as const,
  summaryLabelFg: [85, 85, 85] as const,
  // Alt row
  altRow: [248, 248, 246] as const,
  // Severity
  highFg: [220, 38, 38] as const,
  highBg: [254, 226, 226] as const,
  medFg: [217, 119, 6] as const,
  medBg: [254, 243, 199] as const,
  lowFg: [140, 140, 140] as const,
  lowBg: [240, 240, 240] as const,
  // Status
  good: [22, 163, 74] as const,
  needsAttn: [220, 38, 38] as const,
  borderline: [217, 119, 6] as const,
  // Fix block
  fixBg: [248, 248, 246] as const,
  fixBorder: [17, 17, 17] as const,
  // What works
  greenAccent: [22, 163, 74] as const,
};

const modeLabels: Record<string, string> = {
  technical: "Technical Analysis",
  musical: "Musical Analysis",
  perception: "Perception Analysis",
};

const modeWhatWorksLabel: Record<string, string> = {
  technical: "What Works",
  musical: "What Lands",
  perception: "What Translates",
};

const modeFixOneLabel: Record<string, string> = {
  technical: "If You Fix Only One Thing",
  musical: "Focus Here",
  perception: "Urgent Fix",
};

// ─── Footer on every page ───
function addFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const footerY = PAGE_H - 10;
  doc.setDrawColor(...C.lightDivider);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, footerY - 4, PAGE_W - MARGIN_R, footerY - 4);
  doc.setFontSize(6);
  doc.setFont(MONO, "normal");
  doc.setTextColor(...C.muted);
  doc.text("GENERATED BY SECONDEAR", MARGIN_L, footerY, { charSpace: 0.8 });
  doc.text(`${pageNum} / ${totalPages}`, PAGE_W - MARGIN_R, footerY, { align: "right" });
}

// ─── Page break check ───
function checkPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_H - 20) {
    doc.addPage();
    return MARGIN_L + 4;
  }
  return y;
}

// ─── Wrapped text ───
function addWrapped(doc: jsPDF, text: string, x: number, y: number, maxW: number, lh = LINE_H): number {
  const lines = doc.splitTextToSize(text, maxW) as string[];
  for (const line of lines) {
    y = checkPage(doc, y, lh);
    doc.text(line, x, y);
    y += lh;
  }
  return y;
}

// ─── Section title (uppercase monospace + full-width divider) ───
function sectionTitle(doc: jsPDF, title: string, y: number): number {
  y = checkPage(doc, y, 16);
  y += 6; // margin-top: ~32px equivalent at mm scale
  doc.setFontSize(7);
  doc.setFont(MONO, "bold");
  doc.setTextColor(...C.label);
  doc.text(title.toUpperCase(), MARGIN_L, y, { charSpace: 1.4 });
  y += 2.5;
  doc.setDrawColor(...C.divider);
  doc.setLineWidth(0.25);
  doc.line(MARGIN_L, y, PAGE_W - MARGIN_R, y);
  y += 5;
  return y;
}

// ─── Severity badge ───
function drawSeverityBadge(doc: jsPDF, severity: string, x: number, y: number): number {
  const s = severity.toLowerCase();
  let bg: readonly number[], fg: readonly number[], label: string;
  if (s === "high") {
    bg = C.highBg; fg = C.highFg; label = "HIGH";
  } else if (s === "medium" || s === "med") {
    bg = C.medBg; fg = C.medFg; label = "MED";
  } else {
    bg = C.lowBg; fg = C.lowFg; label = "LOW";
  }
  doc.setFontSize(5.5);
  doc.setFont(MONO, "bold");
  const tw = doc.getTextWidth(label) + 3.5;
  const pillH = 4;
  const pillY = y - 3;
  doc.setFillColor(bg[0], bg[1], bg[2]);
  doc.roundedRect(x, pillY, tw, pillH, 0.8, 0.8, "F");
  doc.setTextColor(fg[0], fg[1], fg[2]);
  doc.text(label, x + 1.75, y);
  return x + tw + 1.5;
}

// ─── Category badge ───
function drawCategoryBadge(doc: jsPDF, cat: string, x: number, y: number): number {
  doc.setFontSize(5.5);
  doc.setFont(MONO, "bold");
  const label = cat.toUpperCase();
  const tw = doc.getTextWidth(label) + 3.5;
  const pillH = 4;
  const pillY = y - 3;
  doc.setFillColor(240, 240, 238);
  doc.roundedRect(x, pillY, tw, pillH, 0.8, 0.8, "F");
  doc.setTextColor(85, 85, 85);
  doc.text(label, x + 1.75, y);
  return x + tw + 1.5;
}

// ─── Status badge with filled square ───
function drawStatusBadge(doc: jsPDF, status: string, x: number, y: number): number {
  const s = status.toLowerCase();
  let fg: readonly number[];
  if (s.includes("good") || s.includes("balanced")) {
    fg = C.good;
  } else if (s.includes("needs") || s.includes("clipping") || s.includes("compressed")) {
    fg = C.needsAttn;
  } else if (s.includes("acceptable") || s.includes("borderline") || s.includes("review") || s.includes("wide")) {
    fg = C.borderline;
  } else {
    fg = C.lowFg;
  }

  // Filled square indicator
  doc.setFillColor(fg[0], fg[1], fg[2]);
  doc.rect(x, y - 2.5, 2.5, 2.5, "F");

  doc.setFontSize(7);
  doc.setFont(MONO, "bold");
  doc.setTextColor(fg[0], fg[1], fg[2]);
  doc.text(status.toUpperCase(), x + 4, y, { charSpace: 0.6 });

  return x + 4 + doc.getTextWidth(status.toUpperCase()) + 2;
}

// ─── Waveform visualization ───
function drawWaveform(doc: jsPDF, items: { timestampSec: number; title: string }[], y: number): number {
  if (items.length === 0) return y;
  y = checkPage(doc, y, 22);

  const barX = MARGIN_L;
  const barW = CONTENT_W;
  const barH = 5;
  const maxSec = Math.max(...items.map(i => i.timestampSec), 60);

  // Track bar
  doc.setFillColor(225, 225, 225);
  doc.roundedRect(barX, y, barW, barH, 1.2, 1.2, "F");
  doc.setFillColor(235, 235, 235);
  doc.roundedRect(barX, y + 0.8, barW, barH - 1.6, 0.8, 0.8, "F");

  // Markers
  for (const item of items) {
    const ratio = Math.min(item.timestampSec / maxSec, 1);
    const mx = barX + ratio * barW;
    doc.setDrawColor(...C.highFg);
    doc.setLineWidth(0.5);
    doc.line(mx, y - 1, mx, y + barH + 1);
    doc.setFillColor(...C.highFg);
    doc.circle(mx, y + barH / 2, 0.8, "F");
  }

  y += barH + 3;
  doc.setFontSize(4.5);
  doc.setFont(MONO, "normal");
  doc.setTextColor(...C.label);
  const maxLabels = Math.min(items.length, 8);
  for (let i = 0; i < maxLabels; i++) {
    const item = items[i];
    const ratio = Math.min(item.timestampSec / maxSec, 1);
    const mx = barX + ratio * barW;
    const label = item.title.length > 18 ? item.title.slice(0, 17) + "…" : item.title;
    const labelY = y + (i % 2 === 0 ? 0 : 3.5);
    doc.text(label, Math.min(Math.max(mx - 4, barX), barX + barW - 20), labelY);
  }
  return y + 9;
}

// ════════════════════════════════════════════════════════════════
// MAIN EXPORT
// ════════════════════════════════════════════════════════════════
export function exportAnalysisPdf(n: NormalizedFeedback, releaseReadiness: string | null) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 0;

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // ═══════════════════════════════════════════
  // HEADER — black bar
  // ═══════════════════════════════════════════
  const headerH = 14;
  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, PAGE_W, headerH, "F");

  // Left: block char + SECONDEAR
  doc.setFontSize(8);
  doc.setFont(MONO, "bold");
  doc.setTextColor(...C.headerFg);
  doc.text("SECONDEAR", MARGIN_L, 9, { charSpace: 1.8 });

  // Right: date + mode
  doc.setFontSize(6.5);
  doc.setFont(MONO, "normal");
  doc.setTextColor(160, 160, 160);
  const modeBadge = (modeLabels[n.mode] || n.mode).toUpperCase();
  doc.text(`${dateStr}  |  ${modeBadge}`, PAGE_W - MARGIN_R, 9, { align: "right" });

  y = headerH + 3;

  // Thin separator
  doc.setDrawColor(...C.divider);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, y, PAGE_W - MARGIN_R, y);
  y += 10;

  // ═══════════════════════════════════════════
  // TRACK NAME — big, bold, uppercase
  // ═══════════════════════════════════════════
  doc.setFontSize(18);
  doc.setFont(MONO, "bold");
  doc.setTextColor(...C.black);
  const trackName = n.trackName.toUpperCase();
  const trackLines = doc.splitTextToSize(trackName, CONTENT_W) as string[];
  for (const tl of trackLines) {
    doc.text(tl, MARGIN_L, y);
    y += 8;
  }

  // Subtitle
  doc.setFontSize(7.5);
  doc.setFont(MONO, "normal");
  doc.setTextColor(...C.label);
  doc.text(`${modeLabels[n.mode] || n.mode}  ·  ${dateStr}`, MARGIN_L, y, { charSpace: 0.6 });
  y += 10;

  // ═══════════════════════════════════════════
  // EXECUTIVE SUMMARY TABLE
  // ═══════════════════════════════════════════
  const chips: { label: string; value: string }[] = [];
  if (n.topIssue) chips.push({ label: "TOP ISSUE", value: n.topIssue });
  if (n.biggestWin) chips.push({ label: "BIGGEST WIN", value: n.biggestWin });
  if (releaseReadiness) chips.push({ label: "RELEASE", value: releaseReadiness });

  if (chips.length > 0) {
    const tableX = MARGIN_L;
    const labelColW = 32;
    const valueColW = CONTENT_W - labelColW;
    const rowH = 7.5;

    // Outer border
    doc.setDrawColor(...C.summaryBorder);
    doc.setLineWidth(0.5);
    doc.rect(tableX, y, CONTENT_W, rowH * chips.length);

    for (let i = 0; i < chips.length; i++) {
      const rowY = y + i * rowH;
      // Label cell bg
      doc.setFillColor(...C.summaryLabelBg);
      doc.rect(tableX, rowY, labelColW, rowH, "F");

      // Horizontal divider between rows
      if (i > 0) {
        doc.setDrawColor(...C.summaryBorder);
        doc.setLineWidth(0.15);
        doc.line(tableX, rowY, tableX + CONTENT_W, rowY);
      }

      // Vertical divider
      doc.setDrawColor(...C.summaryBorder);
      doc.setLineWidth(0.15);
      doc.line(tableX + labelColW, rowY, tableX + labelColW, rowY + rowH);

      // Label text
      doc.setFontSize(6);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...C.summaryLabelFg);
      doc.text(chips[i].label, tableX + 3, rowY + 5, { charSpace: 0.7 });

      // Value text
      doc.setFontSize(8.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...C.black);
      doc.text(chips[i].value, tableX + labelColW + 4, rowY + 5);
    }

    // Re-draw outer border on top
    doc.setDrawColor(...C.summaryBorder);
    doc.setLineWidth(0.5);
    doc.rect(tableX, y, CONTENT_W, rowH * chips.length);

    y += rowH * chips.length + 8;
  }

  // ═══════════════════════════════════════════
  // WAVEFORM VISUALIZATION
  // ═══════════════════════════════════════════
  if (n.timelineItems.length > 0) {
    y = drawWaveform(doc, n.timelineItems, y);
  }

  // ═══════════════════════════════════════════
  // OVERALL IMPRESSION
  // ═══════════════════════════════════════════
  if (n.overallImpression) {
    y = sectionTitle(doc, "Overall Impression", y);
    doc.setFontSize(8);
    doc.setFont(MONO, "normal");
    doc.setTextColor(...C.body);
    y = addWrapped(doc, n.overallImpression, MARGIN_L, y, CONTENT_W, 4.8);
    y += 4;
  }

  // ═══════════════════════════════════════════
  // TIMELINE FEEDBACK
  // ═══════════════════════════════════════════
  if (n.timelineItems.length > 0) {
    y = sectionTitle(doc, "Timeline Feedback", y);

    for (let idx = 0; idx < n.timelineItems.length; idx++) {
      const item = n.timelineItems[idx];
      y = checkPage(doc, y, 22);

      // Line 1: item number + timestamp + severity + category
      const num = String(idx + 1).padStart(2, "0");
      const ts = item.timestampSec >= 0 ? item.timestamp : "";

      doc.setFontSize(6.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...C.label);
      let lineX = MARGIN_L;
      doc.text(num, lineX, y);
      lineX += 7;
      if (ts) {
        doc.text(ts, lineX, y);
        lineX += doc.getTextWidth(ts) + 3;
      }

      // Severity badge
      if (item.severity) {
        lineX = drawSeverityBadge(doc, item.severity, lineX, y);
      }
      // Category badge
      if (item.category) {
        lineX = drawCategoryBadge(doc, item.category, lineX, y);
      }
      y += 5;

      // Title
      doc.setFontSize(10);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...C.black);
      y = addWrapped(doc, item.title, MARGIN_L, y, CONTENT_W, 5.5);

      // Thin separator under title
      doc.setDrawColor(...C.divider);
      doc.setLineWidth(0.15);
      doc.line(MARGIN_L, y, PAGE_W - MARGIN_R, y);
      y += 3;

      // Description
      if (item.description) {
        doc.setFontSize(8);
        doc.setFont(MONO, "normal");
        doc.setTextColor(...C.body);
        y = addWrapped(doc, item.description, MARGIN_L, y, CONTENT_W, 4.8);
        y += 2;
      }

      // FIX block
      if (item.actionText) {
        y = checkPage(doc, y, 12);
        const fixStartY = y - 1;

        // FIX label
        doc.setFontSize(5.5);
        doc.setFont(MONO, "bold");
        doc.setTextColor(...C.fixLabel);
        doc.text("FIX", MARGIN_L + 5, y, { charSpace: 1.0 });
        y += 3.5;

        // Fix text
        doc.setFontSize(7.5);
        doc.setFont(MONO, "normal");
        doc.setTextColor(...C.body);
        const fixTextStartY = y;
        y = addWrapped(doc, item.actionText, MARGIN_L + 5, y, CONTENT_W - 7, 4.5);

        // Background + left border (drawn behind — jsPDF limitation, draw after but use low opacity effect)
        const fixH = y - fixStartY + 2;
        doc.setFillColor(...C.fixBg);
        doc.rect(MARGIN_L + 1, fixStartY, CONTENT_W - 1, fixH, "F");

        // Re-draw text on top of background
        doc.setFontSize(5.5);
        doc.setFont(MONO, "bold");
        doc.setTextColor(...C.fixLabel);
        doc.text("FIX", MARGIN_L + 5, fixStartY + 1, { charSpace: 1.0 });
        doc.setFontSize(7.5);
        doc.setFont(MONO, "normal");
        doc.setTextColor(...C.body);
        // Re-render wrapped text
        const fixLines = doc.splitTextToSize(item.actionText, CONTENT_W - 7) as string[];
        let fy = fixTextStartY;
        for (const fl of fixLines) {
          doc.text(fl, MARGIN_L + 5, fy);
          fy += 4.5;
        }

        // Left accent border
        doc.setDrawColor(...C.fixBorder);
        doc.setLineWidth(1);
        doc.line(MARGIN_L + 1, fixStartY, MARGIN_L + 1, fixStartY + fixH);

        y += 2;
      }
      y += 4;
    }
    y += 2;
  }

  // ═══════════════════════════════════════════
  // TECHNICAL METRICS TABLE
  // ═══════════════════════════════════════════
  const m = n.metrics;
  const metricEntries: { label: string; value: string; status: string }[] = [];
  if (m.integratedLufs !== null)
    metricEntries.push({ label: "Integrated LUFS", value: `${m.integratedLufs.toFixed(1)} LUFS`, status: getMetricStatus("lufs", m.integratedLufs) });
  if (m.shortTermLufs !== null)
    metricEntries.push({ label: "Short-Term LUFS", value: `${m.shortTermLufs.toFixed(1)} LUFS`, status: getMetricStatus("stlufs", m.shortTermLufs) });
  if (m.dynamicRange !== null)
    metricEntries.push({ label: "Dynamic Range", value: `${m.dynamicRange.toFixed(1)} dB`, status: getMetricStatus("dr", m.dynamicRange) });
  if (m.peakDbtp !== null)
    metricEntries.push({ label: "Peak dBTP", value: `${m.peakDbtp.toFixed(1)} dBTP`, status: getMetricStatus("peak", m.peakDbtp) });
  if (m.stereoCorrelation !== null)
    metricEntries.push({ label: "Stereo Correlation", value: m.stereoCorrelation.toFixed(2), status: getMetricStatus("stereo", m.stereoCorrelation) });
  if (m.crestFactor !== null)
    metricEntries.push({ label: "Crest Factor", value: `${m.crestFactor.toFixed(1)} dB`, status: getMetricStatus("crest", m.crestFactor) });
  if (m.subKickRatio !== null)
    metricEntries.push({ label: "Sub/Kick Ratio", value: m.subKickRatio.toFixed(2), status: getMetricStatus("sub", m.subKickRatio) });

  if (metricEntries.length > 0) {
    y = sectionTitle(doc, "Technical Metrics", y);

    const colLabel = MARGIN_L;
    const colValue = MARGIN_L + 55;
    const colStatus = MARGIN_L + 90;
    const rowH = 7;

    // Table header row — dark background
    const headerRowH = 6;
    doc.setFillColor(...C.headerBg);
    doc.rect(MARGIN_L, y - 3.5, CONTENT_W, headerRowH, "F");
    doc.setFontSize(6);
    doc.setFont(MONO, "bold");
    doc.setTextColor(...C.headerFg);
    doc.text("METRIC", colLabel + 2, y, { charSpace: 0.7 });
    doc.text("VALUE", colValue + 2, y, { charSpace: 0.7 });
    doc.text("STATUS", colStatus + 2, y, { charSpace: 0.7 });
    y += headerRowH;

    for (let i = 0; i < metricEntries.length; i++) {
      y = checkPage(doc, y, rowH);
      const me = metricEntries[i];

      // Alternating row bg
      if (i % 2 === 1) {
        doc.setFillColor(...C.altRow);
        doc.rect(MARGIN_L, y - 3.5, CONTENT_W, rowH, "F");
      }

      // Label
      doc.setFontSize(7);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...C.dark);
      doc.text(me.label, colLabel + 2, y);

      // Value
      doc.setFont(MONO, "bold");
      doc.setTextColor(...C.black);
      doc.text(me.value, colValue + 2, y);

      // Status with square indicator
      drawStatusBadge(doc, me.status, colStatus + 2, y);

      y += rowH;
    }
    y += 6;
  }

  // ═══════════════════════════════════════════
  // DEEP READ / FULL ANALYSIS
  // ═══════════════════════════════════════════
  const faCards = getFullAnalysisCards(n);
  const hasFA = faCards.some((c) => c.text);
  if (hasFA) {
    y = sectionTitle(doc, "Deep Read", y);
    for (const card of faCards) {
      if (!card.text) continue;
      y = checkPage(doc, y, 16);

      // Sub-section title
      doc.setFontSize(7);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...C.black);
      doc.text(card.label.toUpperCase(), MARGIN_L, y, { charSpace: 0.9 });
      y += 2;
      doc.setDrawColor(...C.lightDivider);
      doc.setLineWidth(0.2);
      doc.line(MARGIN_L, y, PAGE_W - MARGIN_R, y);
      y += 4;

      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...C.body);
      y = addWrapped(doc, card.text, MARGIN_L, y, CONTENT_W, 4.5);
      y += 4;
    }
    y += 2;
  }

  // ═══════════════════════════════════════════
  // WHAT WORKS — green left accent
  // ═══════════════════════════════════════════
  if (n.whatWorks.length > 0) {
    y = sectionTitle(doc, modeWhatWorksLabel[n.mode] || "What Works", y);
    for (const item of n.whatWorks) {
      y = checkPage(doc, y, 14);

      const itemStartY = y - 2;

      // Title
      doc.setFontSize(9);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...C.black);
      doc.text(item.title, MARGIN_L + 5, y);
      y += 5;

      // Description
      if (item.description) {
        doc.setFontSize(7.5);
        doc.setFont(MONO, "normal");
        doc.setTextColor(85, 85, 85);
        y = addWrapped(doc, item.description, MARGIN_L + 5, y, CONTENT_W - 5, 4.5);
      }

      // Green left accent
      const itemH = y - itemStartY + 1;
      doc.setDrawColor(...C.greenAccent);
      doc.setLineWidth(1);
      doc.line(MARGIN_L + 1, itemStartY, MARGIN_L + 1, itemStartY + itemH);

      y += 4;
    }
    y += 2;
  }

  // ═══════════════════════════════════════════
  // FIX ONE THING
  // ═══════════════════════════════════════════
  if (n.ifFixOneThing && (n.ifFixOneThing.title || n.ifFixOneThing.how)) {
    y = sectionTitle(doc, modeFixOneLabel[n.mode] || "If You Fix Only One Thing", y);
    y = checkPage(doc, y, 18);

    const boxStart = y - 2;
    let boxContent = y;

    if (n.ifFixOneThing.title) {
      doc.setFontSize(9);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...C.highFg);
      doc.text(n.ifFixOneThing.title, MARGIN_L + 5, boxContent);
      boxContent += 5.5;
    }
    if (n.ifFixOneThing.why) {
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...C.body);
      boxContent = addWrapped(doc, "Why: " + n.ifFixOneThing.why, MARGIN_L + 5, boxContent, CONTENT_W - 8, 4.5);
      boxContent += 1;
    }
    if (n.ifFixOneThing.how) {
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...C.body);
      boxContent = addWrapped(doc, "How: " + n.ifFixOneThing.how, MARGIN_L + 5, boxContent, CONTENT_W - 8, 4.5);
    }

    // Red left accent line
    const boxH = boxContent - boxStart + 2;
    doc.setDrawColor(...C.highFg);
    doc.setLineWidth(1);
    doc.line(MARGIN_L + 1, boxStart, MARGIN_L + 1, boxStart + boxH);

    y = boxContent + 6;
  }

  // ═══════════════════════════════════════════
  // YOUR FOCUS
  // ═══════════════════════════════════════════
  if (n.yourFocus.question) {
    y = sectionTitle(doc, "Your Focus", y);
    y = checkPage(doc, y, 14);

    doc.setFontSize(6);
    doc.setFont(MONO, "bold");
    doc.setTextColor(...C.label);
    doc.text("YOU ASKED", MARGIN_L, y, { charSpace: 0.8 });
    y += 4.5;
    doc.setFontSize(7.5);
    doc.setFont(MONO, "normal");
    doc.setTextColor(...C.body);
    y = addWrapped(doc, `"${n.yourFocus.question}"`, MARGIN_L + 2, y, CONTENT_W - 2, 4.5);
    y += 2;
    if (n.yourFocus.response) {
      doc.setFontSize(6);
      doc.setFont(MONO, "bold");
      doc.setTextColor(...C.label);
      doc.text("RESPONSE", MARGIN_L, y, { charSpace: 0.8 });
      y += 4.5;
      doc.setFontSize(7.5);
      doc.setFont(MONO, "normal");
      doc.setTextColor(...C.body);
      y = addWrapped(doc, n.yourFocus.response, MARGIN_L + 2, y, CONTENT_W - 2, 4.5);
    }
  }

  // ═══════════════════════════════════════════
  // FOOTERS on all pages
  // ═══════════════════════════════════════════
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i, pageCount);
  }

  const safeName = n.trackName.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 40);
  doc.save(`SecondEar_${safeName}.pdf`);
}

// ─── Helpers ───

function getFullAnalysisCards(n: NormalizedFeedback) {
  const fa = n.fullAnalysis;
  if (n.mode === "musical") {
    return [
      { label: "Energy Arc", text: fa.energyArc },
      { label: "Section Contrast", text: fa.sectionContrast },
      { label: "Groove Continuity", text: fa.grooveContinuity },
      { label: "Hook Clarity", text: fa.hookClarity },
    ];
  }
  if (n.mode === "perception") {
    return [
      { label: "Sub & Low Translation", text: fa.subLowTranslation },
      { label: "Headroom & Transients", text: fa.headroomTransients },
      { label: "Stereo Fold-Down", text: fa.stereoFoldDown },
      { label: "Listener Fatigue", text: fa.listenerFatigue },
    ];
  }
  return [
    { label: "Mix Balance", text: fa.mixBalance },
    { label: "Dynamics & Loudness", text: fa.dynamics },
    { label: "Stereo & Space", text: fa.stereoSpace },
    { label: "Frequency Balance", text: fa.frequencyBalance },
  ];
}

function getMetricStatus(type: string, val: number): string {
  switch (type) {
    case "lufs":
      if (val >= -14 && val <= -9) return "Good";
      if (val >= -16 && val <= -7) return "Acceptable";
      return "Needs attention";
    case "stlufs":
      if (val >= -12 && val <= -7) return "Good";
      return "Review";
    case "dr":
      if (val >= 6 && val <= 14) return "Good";
      if (val >= 4) return "Acceptable";
      return "Needs attention";
    case "peak":
      if (val <= -1) return "Good";
      if (val <= 0) return "Borderline";
      return "Clipping";
    case "stereo":
      if (val >= 0.5) return "Good";
      if (val >= 0.2) return "Wide";
      return "Very wide";
    case "crest":
      if (val >= 8 && val <= 18) return "Good";
      if (val >= 5) return "Acceptable";
      return "Compressed";
    case "sub":
      if (val >= 0.3 && val <= 0.7) return "Balanced";
      return "Review";
    default:
      return "";
  }
}
